In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
data=pd.read_csv('train.csv')

In [18]:
data.head()

Severity  Safety_Score  \
0                Minor_Damage_And_Injuries     49.223744   
1                Minor_Damage_And_Injuries     62.465753   
2        Significant_Damage_And_Fatalities     63.059361   
3  Significant_Damage_And_Serious_Injuries     48.082192   
4        Significant_Damage_And_Fatalities     26.484018   

   Days_Since_Inspection  Total_Safety_Complaints  Control_Metric  \
0                     14                       22       71.285324   
1                     10                       27       72.288058   
2                     13                       16       66.362808   
3                     11                        9       74.703737   
4                     13                       25       47.948952   

   Turbulence_In_gforces  Cabin_Temperature  Accident_Type_Code  \
0               0.272118              78.04                   2   
1               0.423939              84.54                   2   
2               0.322604              78.86                   7   
3               0.337029              81.79                   3   
4               0.541140              77.16                   3   

   Max_Elevation  Violations  Adverse_Weather_Metric  
0   31335.476824           3                0.424352  
1   26024.711057           2                0.352350  
2   39269.053927           3                0.003364  
3   42771.499200           1                0.211728  
4   35509.228515           2                0.176883

In [8]:
data.shape

(10000, 12)

In [11]:
len(data['Accident_ID'].unique())

10000

In [12]:
del data["Accident_ID"]

In [16]:
(data['Accident_Type_Code'].unique())

array([3, 2, 1, 0, 4, 5], dtype=int64)

In [19]:
y=data["Severity"]

In [20]:
del data["Severity"]

In [22]:
data.head()

Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0     49.223744                     14                       22   
1     62.465753                     10                       27   
2     63.059361                     13                       16   
3     48.082192                     11                        9   
4     26.484018                     13                       25   

   Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0       71.285324               0.272118              78.04   
1       72.288058               0.423939              84.54   
2       66.362808               0.322604              78.86   
3       74.703737               0.337029              81.79   
4       47.948952               0.541140              77.16   

   Accident_Type_Code  Max_Elevation  Violations  Adverse_Weather_Metric  
0                   2   31335.476824           3                0.424352  
1                   2   26024.711057           2                0.352350  
2                   7   39269.053927           3                0.003364  
3                   3   42771.499200           1                0.211728  
4                   3   35509.228515           2                0.176883

In [30]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y)
label=le.transform(y)

In [35]:
label[0:10]

array([1, 1, 2, 3, 2, 1, 0, 1, 0, 3], dtype=int64)

In [36]:
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
X_train_scaled = scaler.fit_transform(data)

In [40]:
X_train_scaled

array([[0.49223744, 0.59090909, 0.40740741, ..., 0.48063219, 0.6       ,
        0.17929156],
       [0.62465753, 0.40909091, 0.5       , ..., 0.39695322, 0.4       ,
        0.14884749],
       [0.63059361, 0.54545455, 0.2962963 , ..., 0.60563743, 0.6       ,
        0.00128854],
       ...,
       [0.27853881, 0.72727273, 0.01851852, ..., 0.51902316, 0.6       ,
        0.07097345],
       [0.56210046, 0.31818182, 0.        , ..., 0.61432501, 0.4       ,
        0.01102064],
       [0.5       , 0.54545455, 0.05555556, ..., 0.39664773, 0.4       ,
        0.00706936]])

In [41]:
from sklearn.svm import SVC  ##support vector machine for classification
clf = SVC(C=10,kernel='rbf').fit(X_train_scaled,label)
print(clf.score(X_train_scaled,label))

0.7472


In [43]:
data_test=pd.read_csv("test.csv")

In [48]:
index=data_test["Accident_ID"]
del data_test["Accident_ID"]

In [50]:
data_test_scaled=scaler.transform(data_test)

In [53]:
pred=clf.predict(data_test_scaled)

In [55]:
pred=list(le.inverse_transform(pred))

C:\Users\PIYUSH\AppData\Local\Programs\Python\Python36\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [60]:
pred

ignificant_Damage_And_Serious_Injuries',
 'Minor_Damage_And_Injuries',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Fatalities',
 'Minor_Damage_And_Injuries',
 'Minor_Damage_And_Injuries',
 'Minor_Damage_And_Injuries',
 'Minor_Damage_And_Injuries',
 'Minor_Damage_And_Injuries',
 'Minor_Damage_And_Injuries',
 'Significant_Damage_And_Serious_Injuries',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Fatalities',
 'Significant_Damage_And_Serious_Injuries',
 'Minor_Damage_And_Injuries',
 'Highly_Fatal_And_Damaging',
 'Highly_Fatal_And_Damaging',
 'Minor_Damage_And_Injuries',
 'Minor_Damage_And_Injuries',
 'Highly_Fatal_And_Damaging',
 'Significant_Damage_And_Fatalities',
 'Highly_Fatal_And_Damaging',
 'Minor_Damage_And_Injuri

In [95]:
submit_score=pd.DataFrame()
submit_score["Accident_ID"]=index

In [96]:
submit_score=submit_score.drop(submit_score.index[-1])

In [97]:
submit_score["Severity"]=pred

In [99]:
submit_score.head()

Accident_ID                                 Severity
0           1                Highly_Fatal_And_Damaging
1          10        Significant_Damage_And_Fatalities
2          14  Significant_Damage_And_Serious_Injuries
3          17                Highly_Fatal_And_Damaging
4          21                Highly_Fatal_And_Damaging

In [101]:
export_csv = submit_score.to_csv (r'pred.csv', index = None, header=True)